INSERT INTO campus VALUES 
(1,'F.E. Dubose Campus', '1', 'FE'),        
(2,'Kershaw County Campus', '1', 'KW'), 
(3,'Lee County Campus', '1', 'LE'), 
(4,'Barton Campus', '2', 'BA'), 
(5,'Benson Campus', '2', 'BE'), 
(6,'Northwest Campus', '2', 'NW'), 
(7,'Pageland Campus', '4', 'PG'), 
(8,'Cheraw Campus', '4', 'CW'), 
(9,'Dillon Campus', '4', 'DL'), 
(10,'Bennettsville Campus', '4', 'BN'), 
(11,'Brashier Campus', '2', 'BR'), 
(12,'Greenwood Campus', '5', 'GR'), 
(13,'Abbeville Campus', '5', 'AV'), 
(14,'Edgefield Campus', '5', 'EF'), 
(15,'Laurens Campus', '5', 'LR'), 
(16,'McCormick Campus', '5', 'MC'), 
(17,'Mount Pleasant Campus', '6', 'MP'), 
(18,'Berkeley Campus', '6', 'BK'), 
(19,'Palmer Campus', '6', 'PM'), 
(20,'North Charleston Campus', '6', 'NC'), 
(21,'Dorchester County Campus', '6', 'DR'), 
(22,'Chester Campus', '8', 'CH'), 
(23,'Indian Land Campus', '8', 'IN'), 
(24,'Batesburg-Leesville Campus', '3', 'BL'), 
(25,'Harbison Campus', '3', 'HB'), 
(26,'Beltline Campus', '3', 'BT'), 
(27,'Airport Campus', '3', 'AR'), 
(28,'Fairfield Campus', '3', 'FD'), 
(29,'Pendleton Campus', '7', 'PN'), 
(30,'Anderson Campus', '7', 'AN'), 
(31,'Easley Campus', '7', 'EA'), 
(32,'Oconee Campus', '7', 'OC'), 
(33,'Conway Campus', '9', 'CN'), 
(34,'Georgetown Campus', '9', 'GE'), 
(35,'Grand Strand Campus', '9', 'GS'), 
(36,'Aiken Campus', '10', 'AI'), 
(37,'Denmark Campus', '11', 'DN');



