INSERT INTO department VALUES 
(1,'Business', '1', 'BUS'), 
(2,'Digital Arts', '1', 'ARV'), 
(3,'Machine Tool Operations', '1', 'MTT'), 
(4,'Information Sciences & Technology', '1', 'IST'), 
(5,'Diesel Engine Technology', '1', 'DHM'), 
(6,'Mechatronics', '1', 'EEM'),
(7,'Outboard Marine Technology', '1', 'MNT'), 
(8,'Dental Hygiene', '1', 'DHG'), 
(9,'Administration', '4', 'ADMN'), 
(10,'General Staff', '2', 'STAFF'), 
(11,'Admissions', '3', 'ADMS'), 
(12,'Medical Coding & Billing', '1', 'HIM'),
(13,'Phlebotomy', '1', 'AHS'), 
(14,'Accounting', '1', 'ACC'), 
(15,'Medical Administrative Assistant', '1', 'AOT'),
(16,'Emergency Medical Technician Paramedic', '1', 'EMS'),
(17,'Nursing', '1', 'NUR'), 
(18,'Computer Technology-Programming', '1', 'CPT'), 
(19,'Criminal Justice Technology', '1', 'CRJ'), 
(20,'Psychology', '1', 'PSYC'), 
(21,'Architectural Technology', '1', 'ARCH'),
(22,'Recordkeeping', '3', 'RDKP'), 
(23,'Presidential Cabinet', '5', 'PRES'), 
(24,'Human Resources', '3', 'HR'),
(25,'Biology', '1', 'BIO'),
(26,'Anthropology', '1', 'ANT'),
(27,'Economics', '1', 'ECO');
