INSERT INTO class_attribute VALUES 
(1,'OFFERED FALL SPRING AND SUMMER'), 
(2,'OFFERED FALL TERM ONLY'), 
(3,'OFFERED SPRING TERM ONLY'), 
(4,'OFFERED SUMMER TERM ONLY'), 
(5,'OFFERED FALL AND SPRING'), 
(6,'OFFERED SPRING AND SUMMER'),
(7,'OFFERED FALL AND SUMMER'), 
(8,'OFFERED MAYMESTER TERM ONLY');